### ISSUE TITLE
help about g-a

### ISSUE THREAD

**Issue by eskuai** [grahammitchell/google-authenticator#2]
Hi, can i ask for you help?

I am trying to understand how works your python script, but i am not sure.

I got a qr code from export process of Google authenticator, Android versión.

But,  what is secret json?

How can i get totp info from qr image?

From export, i got

otpauth-migration://offline?data=:::sometext:::
Then, how can i execute it to get same token code?

What python version?

Tx

**Comment by chencodeX** [comment]
@eskuai 
Your link 
“otpauth-migration://offline?data=:::sometext:::“
is provided by the APP for migration backup. 
You need to use [this project](https://github.com/dim13/otpauth) to convert the URL to an otpauth link.
Then use the secret information that appears in the link to replace the json file in this project.

**Comment by eskuai** [comment]
ok
